version: '3'

services:
  db:
    build:
      context: ./Fichiers/Dockerfiles/mysql
      dockerfile: Dockerfile.mysql
    container_name: mengisen-projetdocker-mysql-server
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    expose:
      - 3306
      - 33060
    command: sh -c "chmod 777 /run/mysqld/mysqld.pid && exec mysqld"

  wordpress:
    build:
      context: ./Fichiers/Dockerfiles/wordpress
      dockerfile: Dockerfile.wordpress
    container_name: mengisen-projetdocker-wordpress
    ports:
      - "8000:80"
    volumes:
      - ./Fichiers/wordpress/themes:/var/www/html/wp-content/themes
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: mengisen-projetdocker-mysql-server
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db-data:







# version: '3'

# services:
#   db:
#     build:
#       context: ./Fichiers/Dockerfiles/mysql
#       dockerfile: Dockerfile.mysql
#     container_name: mengisen-projetdocker-mysql-server
#     ports:
#       - "3307:3306"
#     volumes:
#       - db-data:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: wordpress
#       MYSQL_DATABASE: wordpress
#       MYSQL_USER: wordpress
#       MYSQL_PASSWORD: wordpress
#     # command: '--default-authentication-plugin=mysql_native_password'
#     expose:
#       - 3306
#       - 33060

#   wordpress:
#     build:
#       context: ./Fichiers/Dockerfiles/wordpress
#       dockerfile: Dockerfile.wordpress
#     container_name: mengisen-projetdocker-wordpress
#     ports:
#       - "8000:80"
#     volumes:
#       - ./Fichiers/wordpress/themes:/var/www/html/wp-content/themes
#     depends_on:
#       - db
#     environment:
#       WORDPRESS_DB_HOST: mengisen-projetdocker-mysql
#       WORDPRESS_DB_USER: wordpress
#       WORDPRESS_DB_PASSWORD: wordpress
#       WORDPRESS_DB_NAME: wordpress

# volumes:
#   db-data:
