version: '3'

services:
  db:
    build: ./Fichiers/mysql
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  wordpress:
    build: ./Fichiers/wordpress
    ports:
      - "8000:80"
    volumes:
      - wp-data:/var/www/html
      - ./Fichier/wordpress/themes:/var/www/html/wp-content/themes
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress

volumes:
  db-data:
  wp-data:
