FROM debian:bullseye-slim

# ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y apache2 php libapache2-mod-php php-mysql php-gd php-curl php-json && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN a2enmod rewrite

COPY config/wp-config.php /var/www/html/wp-config.php

EXPOSE 80

CMD ["apache2ctl", "-D", "FOREGROUND"]
